apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crewmeister-challenge.fullname" . }}
  labels:
    {{- include "crewmeister-challenge.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}?createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.username | quote }}
  ACTUATOR_ENDPOINTS: {{ .Values.actuator.endpoints | quote }}
