apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crewmeister-challenge.fullname" . }}
  labels:
    {{- include "crewmeister-challenge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crewmeister-challenge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crewmeister-challenge.selectorLabels" . | nindent 8 }}
        {{- if .Values.keyVault.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: crewmeister-challenge
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "crewmeister-challenge.fullname" . }}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.keyVault.enabled }}
                  name: {{ include "crewmeister-challenge.fullname" . }}-kv
                  {{- else }}
                  name: {{ include "crewmeister-challenge.fullname" . }}
                  {{- end }}
                  key: SPRING_DATASOURCE_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.keyVault.enabled }}
          volumeMounts:
            - name: kv-secrets
              mountPath: /mnt/secrets
              readOnly: true
          {{- end }}
      {{- if .Values.keyVault.enabled }}
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "crewmeister-challenge.fullname" . }}-kv
      {{- end }}
