{{- if and .Values.keyVault.enabled .Values.mysql.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crewmeister-challenge.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv-store
    kind: SecretStore
  target:
    name: mysql-credentials
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: mysql-password
{{- end }}
