{{- if .Values.mysql.deploy }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crewmeister-challenge.labels" . | nindent 4 }}
spec:
  host: mysql.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
