{{- if .Values.keyVault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crewmeister-challenge.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://{{ .Values.keyVault.name }}.vault.azure.net/"
      serviceAccountRef:
        name: crewmeister-challenge
{{- end }}
