apiVersion: v1
kind: ServiceAccount
metadata:
  name: crewmeister-challenge
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crewmeister-challenge.labels" . | nindent 4 }}
  {{- if .Values.keyVault.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVault.workloadIdentityClientId | quote }}
  {{- end }}
