apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: "1.22.0"
    helm:
      releaseName: istiod
      values: |
        meshConfig:
          enableTracing: true
          defaultConfig:
            tracing:
              zipkin:
                address: jaeger-collector.observability.svc.cluster.local:9411
              sampling: 100
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Must sync after istio-base CRDs are ready
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
